# see https://zappr.opensource.zalan.do/
autobranch: false
commit: false
approvals:
  minimum: 1
  ignore: pr_opener
  pattern: "^(:\\+1:|👍)$"
  veto:
    pattern: "^(:\\-1:|👎)$"
  from:
    orgs:
      - wallabag
    collaborators: true
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
    contains-url: false
    contains-issue-number: false
  template:
    differs-from-body: true
